name: Deploy to ECS

on:
  push:
    branches: [master]

env:
  AWS_REGION: eu-west-2
  APP_NAME: atsmatcherbackend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # =========================
      # AWS AUTH
      # =========================
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # =========================
      # LOAD INFRASTRUCTURE VALUES (SSM)
      # =========================
      - name: Load infra outputs from SSM
        run: |
          set -e

          echo "ECR_REPO=$(aws ssm get-parameter --name /$APP_NAME/ecr_repo --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "ECS_CLUSTER=$(aws ssm get-parameter --name /$APP_NAME/ecs_cluster --query Parameter.Value --output text)" >> $GITHUB_ENV
          echo "ECS_SERVICE=$(aws ssm get-parameter --name /$APP_NAME/ecs_service --query Parameter.Value --output text)" >> $GITHUB_ENV

      # =========================
      # LOGIN TO ECR
      # =========================
      - name: Login to Amazon ECR
        run: |
          REGISTRY=$(echo $ECR_REPO | cut -d'/' -f1)

          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $REGISTRY

      # =========================
      # BUILD + PUSH IMAGE
      # =========================
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}

          docker build -t app .
          docker tag app:latest $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:$IMAGE_TAG

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # =========================
      # UPDATE ECS SERVICE
      # =========================
      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION
